#include "defold_backend.h"
#include <sstream>
#include <algorithm>

namespace lex {

std::string DefoldBackend::type_to_table_name(const std::string& type) const {
    // Defold convention: snake_case, plural
    if (type.empty()) return "items";

    std::string result = type;
    std::transform(result.begin(), result.end(), result.begin(),
                   [](unsigned char c) { return std::tolower(c); });

    // Smart pluralization
    if (result.back() == 'y' && result.size() > 1) {
        result.back() = 'i';
        result += "es";
    } else if (result.back() != 's') {
        result += 's';
    }
    return result;
}

std::string DefoldBackend::generate(const std::vector<std::unique_ptr<Definition>>& ast) {
    std::stringstream output;

    output << "-- Auto-generated by Lex Compiler for Defold\n";
    output << "-- Do not edit manually\n\n";

    output << "local M = {}\n\n";

    // Generate helper functions
    output << "-- Condition helper functions\n";
    output << "M.helpers = {}\n\n";

    output << "-- Check if player has a technology researched\n";
    output << "function M.helpers.has_technology(tech_id, state)\n";
    output << "    state = state or M.state\n";
    output << "    return state.technologies and state.technologies[tech_id] == true\n";
    output << "end\n\n";

    output << "-- Check if player has a structure built\n";
    output << "function M.helpers.has_structure(structure_id, state)\n";
    output << "    state = state or M.state\n";
    output << "    return state.structures and state.structures[structure_id] == true\n";
    output << "end\n\n";

    output << "-- Check if player has enough resources\n";
    output << "function M.helpers.has_resources(resource_map, state)\n";
    output << "    state = state or M.state\n";
    output << "    for resource, amount in pairs(resource_map) do\n";
    output << "        local available = (state.resources and state.resources[resource]) or 0\n";
    output << "        if available < amount then return false end\n";
    output << "    end\n";
    output << "    return true\n";
    output << "end\n\n";

    output << "-- Global game state\n";
    output << "M.state = {\n";
    output << "    technologies = {},\n";
    output << "    structures = {},\n";
    output << "    resources = {},\n";
    output << "}\n\n";

    // Collect types
    for (const auto& def : ast) {
        seen_types_.insert(def->definition_type);
    }

    // Generate table declarations
    for (const auto& type : seen_types_) {
        std::string table_name = type_to_table_name(type);
        output << "M." << table_name << " = {}\n";
    }
    output << "\n";

    // Generate each definition
    for (const auto& def : ast) {
        output << generate_definition(*def);
    }

    // Generate Defold-specific helpers
    output << "-- Defold collection factory integration\n";
    output << "function M.get_collection_url(definition_type, id)\n";
    output << "    local table_name = M.type_to_table_name(definition_type)\n";
    output << "    local def = M[table_name] and M[table_name][id]\n";
    output << "    if def and def.collection_url then\n";
    output << "        return def.collection_url\n";
    output << "    end\n";
    output << "    return nil\n";
    output << "end\n\n";

    output << "-- Get all definitions of a type\n";
    output << "function M.get_all(definition_type)\n";
    output << "    local table_name = M.type_to_table_name(definition_type)\n";
    output << "    return M[table_name] or {}\n";
    output << "end\n\n";

    output << "-- Get a specific definition\n";
    output << "function M.get(definition_type, id)\n";
    output << "    local table_name = M.type_to_table_name(definition_type)\n";
    output << "    return M[table_name] and M[table_name][id]\n";
    output << "end\n\n";

    output << "-- Type name converter (exposed for external use)\n";
    output << "function M.type_to_table_name(type_name)\n";
    output << "    if not type_name then return \"items\" end\n";
    output << "    local result = type_name:lower()\n";
    output << "    if result:sub(-1) == \"y\" then\n";
    output << "        result = result:sub(1, -2) .. \"ies\"\n";
    output << "    elseif result:sub(-1) ~= \"s\" then\n";
    output << "        result = result .. \"s\"\n";
    output << "    end\n";
    output << "    return result\n";
    output << "end\n\n";

    // Return module
    output << "return M\n";

    return output.str();
}

std::string DefoldBackend::generate_definition(const Definition& def) {
    std::stringstream lua;
    std::string table_name = type_to_table_name(def.definition_type);

    lua << "M." << table_name << "." << def.identifier << " = {\n";

    // Add id field
    lua << "    id = \"" << def.identifier << "\",\n";

    // Add type field
    lua << "    type = \"" << def.definition_type << "\",\n";

    // Generate all properties
    for (const auto& prop : def.properties) {
        lua << "    " << prop->name << " = " << generate_property_value(*prop) << ",\n";
    }

    // Generate conditions if present
    if (!def.conditions.empty()) {
        lua << "    conditions = {\n";
        for (const auto& cond : def.conditions) {
            lua << generate_condition(cond.get());
        }
        lua << "    },\n";
    }

    lua << "}\n\n";

    // Generate condition checker
    if (!def.conditions.empty()) {
        lua << "function M." << table_name << "." << def.identifier << ":check_conditions(state)\n";
        lua << "    state = state or M.state\n";
        lua << "    local results = {}\n";
        for (const auto& cond : def.conditions) {
            if (cond->trigger == "available_if") {
                lua << "    results.available = results.available or ("
                    << generate_expression(cond->expression.get(), true) << ")\n";
            }
        }
        lua << "    return results\n";
        lua << "end\n\n";
    }

    return lua.str();
}

std::string DefoldBackend::generate_property_value(const Property& prop) {
    if (!prop.value) return "nil";

    switch (prop.value->type) {
        case PropertyValue::Type::EXPRESSION:
            if (prop.value->expression) {
                return generate_expression(prop.value->expression.get());
            }
            return "nil";

        case PropertyValue::Type::RESOURCE_MAP:
            if (prop.value->resource_map) {
                return generate_resource_map(*prop.value->resource_map);
            }
            return "{}";

        case PropertyValue::Type::REFERENCE_LIST:
            if (prop.value->reference_list) {
                return generate_reference_list(*prop.value->reference_list);
            }
            return "{}";

        default:
            return "nil";
    }
}

std::string DefoldBackend::generate_resource_map(const ResourceMap& map) {
    std::string lua = "{";
    bool first = true;
    for (const auto& [name, value] : map.resources) {
        if (!first) lua += ", ";
        lua += name + " = " + std::to_string(static_cast<int>(value));
        first = false;
    }
    lua += "}";
    return lua;
}

std::string DefoldBackend::generate_reference_list(const ReferenceList& list) {
    std::string lua = "{";
    bool first = true;
    for (const auto& ref : list.references) {
        if (!first) lua += ", ";
        lua += "\"" + ref + "\"";
        first = false;
    }
    lua += "}";
    return lua;
}

// ============================================================================
// Expression Generation
// ============================================================================

std::string DefoldBackend::generate_expression(const Expression* expr, bool in_condition) {
    if (!expr) return "nil";

    switch (expr->type) {
        case Expression::Type::INTEGER:
            return std::to_string(std::get<int64_t>(expr->value));

        case Expression::Type::FLOAT:
            return std::to_string(std::get<double>(expr->value));

        case Expression::Type::STRING:
            return "\"" + std::get<std::string>(expr->value) + "\"";

        case Expression::Type::BOOLEAN:
            return std::get<bool>(expr->value) ? "true" : "false";

        case Expression::Type::REFERENCE:
            if (in_condition) {
                return "state." + expr->reference;
            }
            return "\"" + expr->reference + "\"";

        case Expression::Type::BINARY:
            return generate_binary_expression(expr, in_condition);

        case Expression::Type::UNARY:
            return generate_unary_expression(expr, in_condition);

        case Expression::Type::CALL:
            return generate_call_expression(expr, in_condition);

        case Expression::Type::MEMBER:
            return generate_member_expression(expr, in_condition);

        case Expression::Type::COLOR:
            if (std::holds_alternative<std::string>(expr->value)) {
                return "\"" + std::get<std::string>(expr->value) + "\"";
            }
            return "\"\"";

        case Expression::Type::NULL_VAL:
        default:
            return "nil";
    }
}

std::string DefoldBackend::generate_binary_expression(const Expression* expr, bool in_condition) {
    if (!expr || !expr->left || !expr->right) return "nil";

    std::string left = generate_expression(expr->left.get(), in_condition);
    std::string right = generate_expression(expr->right.get(), in_condition);
    std::string op = binary_op_to_lua(expr->binary_op);

    return "(" + left + " " + op + " " + right + ")";
}

std::string DefoldBackend::generate_unary_expression(const Expression* expr, bool in_condition) {
    if (!expr || !expr->operand) return "nil";

    std::string operand = generate_expression(expr->operand.get(), in_condition);
    std::string op = unary_op_to_lua(expr->unary_op);

    return "(" + op + operand + ")";
}

std::string DefoldBackend::generate_call_expression(const Expression* expr, bool in_condition) {
    if (!expr) return "nil";

    std::string func_name = expr->function_name;
    if (func_name == "has_technology" || func_name == "has_structure" || func_name == "has_resources") {
        func_name = "M.helpers." + func_name;
    }

    std::string result = func_name + "(";
    bool first = true;
    for (const auto& arg : expr->arguments) {
        if (!first) result += ", ";
        result += generate_expression(arg.get(), in_condition);
        first = false;
    }
    result += ")";
    return result;
}

std::string DefoldBackend::generate_member_expression(const Expression* expr, bool in_condition) {
    if (!expr || !expr->object) return "nil";

    std::string obj = generate_expression(expr->object.get(), in_condition);
    return obj + "." + expr->member_name;
}

std::string DefoldBackend::generate_condition(const Condition* cond) {
    if (!cond) return "";

    std::stringstream lua;
    lua << "        " << cond->trigger << " = ";

    if (cond->expression && cond->expression->type != Expression::Type::BOOLEAN) {
        lua << "function(state) return "
            << generate_expression(cond->expression.get(), true)
            << " end,\n";
        return lua.str();
    }

    if (!cond->properties.empty()) {
        std::vector<std::string> checks;

        for (const auto& prop : cond->properties) {
            if (prop->name == "technologies" && prop->value &&
                prop->value->type == PropertyValue::Type::REFERENCE_LIST &&
                prop->value->reference_list) {
                for (const auto& tech : prop->value->reference_list->references) {
                    checks.push_back("M.helpers.has_technology(\"" + tech + "\", state)");
                }
            } else if (prop->name == "structures" && prop->value &&
                prop->value->type == PropertyValue::Type::REFERENCE_LIST &&
                prop->value->reference_list) {
                for (const auto& struct_id : prop->value->reference_list->references) {
                    checks.push_back("M.helpers.has_structure(\"" + struct_id + "\", state)");
                }
            } else if (prop->name == "resources" && prop->value &&
                prop->value->type == PropertyValue::Type::RESOURCE_MAP &&
                prop->value->resource_map) {
                checks.push_back("M.helpers.has_resources(" +
                    generate_resource_map(*prop->value->resource_map) + ", state)");
            }
        }

        if (!checks.empty()) {
            std::string condition_expr;
            for (size_t i = 0; i < checks.size(); ++i) {
                if (i > 0) condition_expr += " and ";
                condition_expr += checks[i];
            }
            lua << "function(state) return " << condition_expr << " end,\n";
            return lua.str();
        }
    }

    if (cond->expression) {
        lua << "function(state) return "
            << generate_expression(cond->expression.get(), true)
            << " end,\n";
    } else {
        lua << "true,\n";
    }

    return lua.str();
}

std::string DefoldBackend::binary_op_to_lua(Expression::BinaryOp op) const {
    switch (op) {
        case Expression::BinaryOp::ADD: return "+";
        case Expression::BinaryOp::SUB: return "-";
        case Expression::BinaryOp::MUL: return "*";
        case Expression::BinaryOp::DIV: return "/";
        case Expression::BinaryOp::MOD: return "%";
        case Expression::BinaryOp::EQ: return "==";
        case Expression::BinaryOp::NE: return "~=";
        case Expression::BinaryOp::GT: return ">";
        case Expression::BinaryOp::LT: return "<";
        case Expression::BinaryOp::GE: return ">=";
        case Expression::BinaryOp::LE: return "<=";
        case Expression::BinaryOp::AND: return "and";
        case Expression::BinaryOp::OR: return "or";
        default: return "+";
    }
}

std::string DefoldBackend::unary_op_to_lua(Expression::UnaryOp op) const {
    switch (op) {
        case Expression::UnaryOp::NOT: return "not ";
        case Expression::UnaryOp::NEG: return "-";
        default: return "";
    }
}

std::string DefoldBackend::get_string_property(const Definition& def, const std::string& name) {
    auto result = def.get_string_property(name);
    return result.value_or("");
}

int64_t DefoldBackend::get_int_property(const Definition& def, const std::string& name, int64_t default_val) {
    auto result = def.get_int_property(name);
    return result.value_or(default_val);
}

const ResourceMap* DefoldBackend::get_resource_map_property(const Definition& def, const std::string& name) {
    return def.get_resource_map_property(name);
}

}
