#include "godot_backend.h"
#include <sstream>
#include <algorithm>

namespace lex {

std::string GodotBackend::type_to_var_name(const std::string& type) const {
    if (type.empty()) return "items";

    std::string result = type;
    // Godot convention: snake_case for variables
    std::transform(result.begin(), result.end(), result.begin(),
                   [](unsigned char c) { return std::tolower(c); });

    // Pluralize
    if (result.back() == 'y' && result.size() > 1) {
        result.back() = 'i';
        result += "es";
    } else if (result.back() != 's') {
        result += 's';
    }
    return result;
}

std::string GodotBackend::escape_string(const std::string& s) const {
    std::string result;
    for (char c : s) {
        switch (c) {
            case '"': result += "\\\""; break;
            case '\\': result += "\\\\"; break;
            case '\n': result += "\\n"; break;
            default: result += c;
        }
    }
    return result;
}

std::string GodotBackend::generate(const std::vector<std::unique_ptr<Definition>>& ast) {
    std::stringstream output;

    output << "# Auto-generated by Lex Compiler\n";
    output << "# Do not edit manually\n";
    output << "class_name " << class_name_ << " extends Resource\n\n";

    // Collect types
    for (const auto& def : ast) {
        seen_types_.insert(def->definition_type);
    }

    // Generate dictionary declarations
    for (const auto& type : seen_types_) {
        std::string var_name = type_to_var_name(type);
        output << "var " << var_name << " = {}\n";
    }
    output << "\n";

    // Generate helper functions for condition evaluation
    output << "# Condition helper functions\n";
    output << "# Check if player has a technology researched\n";
    output << "func has_technology(tech_id: String, game_state: Dictionary) -> bool:\n";
    output << "\treturn game_state.has(\"technologies\") and game_state.technologies.has(tech_id)\n\n";

    output << "# Check if player has a structure built\n";
    output << "func has_structure(structure_id: String, game_state: Dictionary) -> bool:\n";
    output << "\treturn game_state.has(\"structures\") and game_state.structures.has(structure_id)\n\n";

    output << "# Check if player has enough resources\n";
    output << "func has_resources(resource_map: Dictionary, game_state: Dictionary) -> bool:\n";
    output << "\tfor resource in resource_map:\n";
    output << "\t\tvar required = resource_map[resource]\n";
    output << "\t\tvar available = game_state.get(\"resources\", {}).get(resource, 0)\n";
    output << "\t\tif available < required:\n";
    output << "\t\t\treturn false\n";
    output << "\treturn true\n\n";

    output << "# Evaluate a condition expression string\n";
    output << "func evaluate_condition(expr: String, game_state: Dictionary) -> bool:\n";
    output << "\tvar e = expr.strip_edges()\n";
    output << "\t# Handle has_technology(X)\n";
    output << "\tif e.begins_with(\"has_technology(\") and e.ends_with(\")\"):\n";
    output << "\t\tvar id = e.substr(16, e.length() - 17)\n";
    output << "\t\treturn has_technology(id, game_state)\n";
    output << "\t# Handle has_structure(X)\n";
    output << "\tif e.begins_with(\"has_structure(\") and e.ends_with(\")\"):\n";
    output << "\t\tvar id = e.substr(14, e.length() - 15)\n";
    output << "\t\treturn has_structure(id, game_state)\n";
    output << "\t# Handle has_resources({...})\n";
    output << "\tif e.begins_with(\"has_resources(\"):\n";
    output << "\t\treturn true # Simplified - parse resource map if needed\n";
    output << "\treturn true\n\n";

    // Generate _init function with data
    output << "func _init():\n";

    for (const auto& def : ast) {
        output << generate_definition(*def);
    }

    output << "\tpass\n\n";

    // Generate check_conditions function for each definition with conditions
    for (const auto& def : ast) {
        if (!def->conditions.empty()) {
            std::string var_name = type_to_var_name(def->definition_type);
            output << "func check_" << var_name << "_" << def->identifier << "(game_state: Dictionary) -> Dictionary:\n";
            output << "\tvar results = {}\n";
            for (const auto& cond : def->conditions) {
                if (cond->expression) {
                    std::string expr_str = generate_expression(cond->expression.get());
                    output << "\tresults[\"" << cond->trigger << "\"] = evaluate_condition(\""
                           << escape_string(expr_str) << "\", game_state)\n";
                }
            }
            output << "\treturn results\n\n";
        }
    }

    return output.str();
}

std::string GodotBackend::generate_definition(const Definition& def) {
    std::stringstream gd;
    std::string var_name = type_to_var_name(def.definition_type);

    gd << "\t" << var_name << "[\"" << def.identifier << "\"] = {\n";

    // ID and type
    gd << "\t\t\"id\": \"" << def.identifier << "\",\n";
    gd << "\t\t\"type\": \"" << def.definition_type << "\",\n";

    // Properties
    for (const auto& prop : def.properties) {
        gd << "\t\t\"" << prop->name << "\": " << generate_property_value(*prop) << ",\n";
    }

    // Conditions (if any)
    if (!def.conditions.empty()) {
        gd << "\t\t\"conditions\": [\n";
        for (size_t i = 0; i < def.conditions.size(); i++) {
            auto& cond = def.conditions[i];
            gd << "\t\t\t{";
            gd << "\"trigger\": \"" << cond->trigger << "\"";
            if (cond->expression) {
                gd << ", \"expr\": \"" << escape_string(generate_expression(cond->expression.get())) << "\"";
            }
            gd << "}";
            if (i < def.conditions.size() - 1) gd << ",";
            gd << "\n";
        }
        gd << "\t\t],\n";
    }

    gd << "\t}\n";

    return gd.str();
}

std::string GodotBackend::generate_property_value(const Property& prop) {
    if (!prop.value) return "null";

    switch (prop.value->type) {
        case PropertyValue::Type::EXPRESSION:
            if (prop.value->expression) {
                auto& expr = prop.value->expression;
                switch (expr->type) {
                    case Expression::Type::STRING:
                        return "\"" + escape_string(std::get<std::string>(expr->value)) + "\"";
                    case Expression::Type::INTEGER:
                        return std::to_string(std::get<int64_t>(expr->value));
                    case Expression::Type::FLOAT:
                        return std::to_string(std::get<double>(expr->value));
                    case Expression::Type::BOOLEAN:
                        return std::get<bool>(expr->value) ? "true" : "false";
                    case Expression::Type::REFERENCE:
                        return "\"" + expr->reference + "\"";
                    case Expression::Type::COLOR:
                        return "\"" + std::get<std::string>(expr->value) + "\"";
                    default:
                        return "\"(expr)\"";
                }
            }
            return "null";

        case PropertyValue::Type::RESOURCE_MAP:
            if (prop.value->resource_map) {
                return generate_resource_map(*prop.value->resource_map);
            }
            return "{}";

        case PropertyValue::Type::REFERENCE_LIST:
            if (prop.value->reference_list) {
                return generate_reference_list(*prop.value->reference_list);
            }
            return "[]";

        default:
            return "null";
    }
}

std::string GodotBackend::generate_resource_map(const ResourceMap& map) {
    std::string result = "{";
    bool first = true;
    for (const auto& [name, value] : map.resources) {
        if (!first) result += ", ";
        result += "\"" + name + "\": " + std::to_string(static_cast<int>(value));
        first = false;
    }
    result += "}";
    return result;
}

std::string GodotBackend::generate_reference_list(const ReferenceList& list) {
    std::string result = "[";
    bool first = true;
    for (const auto& ref : list.references) {
        if (!first) result += ", ";
        result += "\"" + ref + "\"";
        first = false;
    }
    result += "]";
    return result;
}

std::string GodotBackend::generate_expression(const Expression* expr) {
    if (!expr) return "";

    switch (expr->type) {
        case Expression::Type::INTEGER:
            return std::to_string(std::get<int64_t>(expr->value));
        case Expression::Type::FLOAT:
            return std::to_string(std::get<double>(expr->value));
        case Expression::Type::STRING:
            return "\"" + std::get<std::string>(expr->value) + "\"";
        case Expression::Type::BOOLEAN:
            return std::get<bool>(expr->value) ? "true" : "false";
        case Expression::Type::REFERENCE:
            return expr->reference;
        case Expression::Type::BINARY:
            if (expr->left && expr->right) {
                std::string op;
                switch (expr->binary_op) {
                    case Expression::BinaryOp::EQ: op = "=="; break;
                    case Expression::BinaryOp::NE: op = "!="; break;
                    case Expression::BinaryOp::GT: op = ">"; break;
                    case Expression::BinaryOp::LT: op = "<"; break;
                    case Expression::BinaryOp::GE: op = ">="; break;
                    case Expression::BinaryOp::LE: op = "<="; break;
                    case Expression::BinaryOp::AND: op = "and"; break;
                    case Expression::BinaryOp::OR: op = "or"; break;
                    case Expression::BinaryOp::ADD: op = "+"; break;
                    case Expression::BinaryOp::SUB: op = "-"; break;
                    case Expression::BinaryOp::MUL: op = "*"; break;
                    case Expression::BinaryOp::DIV: op = "/"; break;
                    default: op = "?"; break;
                }
                return generate_expression(expr->left.get()) + " " + op + " " +
                       generate_expression(expr->right.get());
            }
            return "";
        case Expression::Type::UNARY:
            if (expr->operand) {
                if (expr->unary_op == Expression::UnaryOp::NOT) {
                    return "not " + generate_expression(expr->operand.get());
                } else if (expr->unary_op == Expression::UnaryOp::NEG) {
                    return "-" + generate_expression(expr->operand.get());
                }
            }
            return "";
        case Expression::Type::CALL:
            if (!expr->function_name.empty()) {
                std::string result = expr->function_name + "(";
                for (size_t i = 0; i < expr->arguments.size(); i++) {
                    if (i > 0) result += ", ";
                    result += generate_expression(expr->arguments[i].get());
                }
                result += ")";
                return result;
            }
            return "";
        case Expression::Type::MEMBER:
            if (expr->object) {
                return generate_expression(expr->object.get()) + "." + expr->member_name;
            }
            return "";
        default:
            return "";
    }
}

}
