#include "love2d_backend.hpp"
#include <sstream>
#include <algorithm>

namespace lex {

std::string Love2DBackend::type_to_table_name(const std::string& type) const {
    // Love2D convention: snake_case, plural
    // "structure" -> "structures", "technology" -> "technologies"
    if (type.empty()) return "items";

    std::string result = type;
    // Convert to lowercase
    std::transform(result.begin(), result.end(), result.begin(),
                   [](unsigned char c) { return std::tolower(c); });

    // Smart pluralization
    if (result.back() == 'y' && result.size() > 1) {
        // technology -> technologies
        result.back() = 'i';
        result += "es";
    } else if (result.back() != 's') {
        result += 's';
    }
    return result;
}

std::string Love2DBackend::generate(const std::vector<std::unique_ptr<Definition>>& ast) {
    std::stringstream output;

    output << "-- Auto-generated by Lex Compiler for LÖVE2D\n";
    output << "-- Do not edit manually\n\n";

    output << "local GameData = {}\n\n";

    // Generate helper functions for condition evaluation
    output << "-- Condition helper functions\n";
    output << "GameData.helpers = {}\n\n";

    output << "-- Check if player has a technology researched\n";
    output << "function GameData.helpers.has_technology(tech_id, state)\n";
    output << "    state = state or GameData.state\n";
    output << "    return state.technologies and state.technologies[tech_id] == true\n";
    output << "end\n\n";

    output << "-- Check if player has a structure built\n";
    output << "function GameData.helpers.has_structure(structure_id, state)\n";
    output << "    state = state or GameData.state\n";
    output << "    return state.structures and state.structures[structure_id] == true\n";
    output << "end\n\n";

    output << "-- Check if player has enough resources\n";
    output << "function GameData.helpers.has_resources(resource_map, state)\n";
    output << "    state = state or GameData.state\n";
    output << "    for resource, amount in pairs(resource_map) do\n";
    output << "        local available = (state.resources and state.resources[resource]) or 0\n";
    output << "        if available < amount then return false end\n";
    output << "    end\n";
    output << "    return true\n";
    output << "end\n\n";

    output << "-- Global game state (initialize before using)\n";
    output << "GameData.state = {\n";
    output << "    technologies = {},\n";
    output << "    structures = {},\n";
    output << "    resources = {},\n";
    output << "}\n\n";

    // First pass: collect all definition types
    for (const auto& def : ast) {
        seen_types_.insert(def->definition_type);
    }

    // Generate table declarations for each type
    for (const auto& type : seen_types_) {
        std::string table_name = type_to_table_name(type);
        output << "GameData." << table_name << " = {}\n";
    }
    output << "\n";

    // Generate each definition
    for (const auto& def : ast) {
        output << generate_definition(*def);
    }

    // Generate load function for love.filesystem
    output << "-- Load game data from file (optional, for hot reload)\n";
    output << "function GameData.load(path)\n";
    output << "    local chunk = love.filesystem.load(path)\n";
    output << "    if chunk then\n";
    output << "        local data = chunk()\n";
    output << "        for k, v in pairs(data) do\n";
    output << "            GameData[k] = v\n";
    output << "        end\n";
    output << "    end\n";
    output << "end\n\n";

    // Generate save function
    output << "-- Save game state\n";
    output << "function GameData.save_state(path)\n";
    output << "    local serialized = \"return \" .. GameData.serialize(GameData.state)\n";
    output << "    love.filesystem.write(path, serialized)\n";
    output << "end\n\n";

    // Generate simple serializer
    output << "-- Simple table serializer\n";
    output << "function GameData.serialize(tbl, indent)\n";
    output << "    indent = indent or 0\n";
    output << "    local result = \"{\\n\"\n";
    output << "    for k, v in pairs(tbl) do\n";
    output << "        result = result .. string.rep(\"  \", indent + 1)\n";
    output << "        if type(k) == \"string\" then\n";
    output << "            result = result .. k .. \" = \"\n";
    output << "        end\n";
    output << "        if type(v) == \"table\" then\n";
    output << "            result = result .. GameData.serialize(v, indent + 1)\n";
    output << "        elseif type(v) == \"string\" then\n";
    output << "            result = result .. \"\\\"\" .. v .. \"\\\"\"\n";
    output << "        else\n";
    output << "            result = result .. tostring(v)\n";
    output << "        end\n";
    output << "        result = result .. \",\\n\"\n";
    output << "    end\n";
    output << "    return result .. string.rep(\"  \", indent) .. \"}\"\n";
    output << "end\n\n";

    // Return module
    output << "return GameData\n";

    return output.str();
}

std::string Love2DBackend::generate_definition(const Definition& def) {
    return generate_generic(def);
}

std::string Love2DBackend::generate_generic(const Definition& def) {
    std::stringstream lua;
    std::string table_name = type_to_table_name(def.definition_type);

    lua << "GameData." << table_name << "." << def.identifier << " = {\n";

    // Generate all properties dynamically
    for (const auto& prop : def.properties) {
        lua << "    " << prop->name << " = " << generate_property_value(*prop) << ",\n";
    }

    // Generate conditions if present
    if (!def.conditions.empty()) {
        lua << "    conditions = {\n";
        for (const auto& cond : def.conditions) {
            lua << generate_condition(cond.get());
        }
        lua << "    },\n";
    }

    lua << "}\n\n";

    // Generate condition checker function if needed
    if (!def.conditions.empty()) {
        lua << "function GameData." << table_name << "." << def.identifier << ":check_conditions(state)\n";
        lua << "    state = state or GameData.state\n";
        lua << "    local results = {}\n";
        for (const auto& cond : def.conditions) {
            if (cond->trigger == "available_if") {
                lua << "    results.available = results.available or ("
                    << generate_expression(cond->expression.get(), true) << ")\n";
            }
        }
        lua << "    return results\n";
        lua << "end\n\n";
    }

    return lua.str();
}

std::string Love2DBackend::generate_property_value(const Property& prop) {
    if (!prop.value) return "nil";

    switch (prop.value->type) {
        case PropertyValue::Type::EXPRESSION:
            if (prop.value->expression) {
                return generate_expression(prop.value->expression.get());
            }
            return "nil";

        case PropertyValue::Type::RESOURCE_MAP:
            if (prop.value->resource_map) {
                return generate_resource_map(*prop.value->resource_map);
            }
            return "{}";

        case PropertyValue::Type::REFERENCE_LIST:
            if (prop.value->reference_list) {
                return generate_reference_list(*prop.value->reference_list);
            }
            return "{}";

        default:
            return "nil";
    }
}

std::string Love2DBackend::generate_resource_map(const ResourceMap& map) {
    std::string lua = "{";
    bool first = true;
    for (const auto& [name, value] : map.resources) {
        if (!first) lua += ", ";
        lua += name + " = " + std::to_string(static_cast<int>(value));
        first = false;
    }
    lua += "}";
    return lua;
}

std::string Love2DBackend::generate_reference_list(const ReferenceList& list) {
    std::string lua = "{";
    bool first = true;
    for (const auto& ref : list.references) {
        if (!first) lua += ", ";
        lua += "\"" + ref + "\"";
        first = false;
    }
    lua += "}";
    return lua;
}

// ============================================================================
// Expression Generation
// ============================================================================

std::string Love2DBackend::generate_expression(const Expression* expr, bool in_condition) {
    if (!expr) return "nil";

    switch (expr->type) {
        case Expression::Type::INTEGER:
            return std::to_string(std::get<int64_t>(expr->value));

        case Expression::Type::FLOAT:
            return std::to_string(std::get<double>(expr->value));

        case Expression::Type::STRING:
            return "\"" + std::get<std::string>(expr->value) + "\"";

        case Expression::Type::BOOLEAN:
            return std::get<bool>(expr->value) ? "true" : "false";

        case Expression::Type::REFERENCE:
            if (in_condition) {
                return "state." + expr->reference;
            }
            return "\"" + expr->reference + "\"";

        case Expression::Type::BINARY:
            return generate_binary_expression(expr, in_condition);

        case Expression::Type::UNARY:
            return generate_unary_expression(expr, in_condition);

        case Expression::Type::CALL:
            return generate_call_expression(expr, in_condition);

        case Expression::Type::MEMBER:
            return generate_member_expression(expr, in_condition);

        case Expression::Type::COLOR:
            if (std::holds_alternative<std::string>(expr->value)) {
                return "\"" + std::get<std::string>(expr->value) + "\"";
            }
            return "\"\"";

        case Expression::Type::NULL_VAL:
        default:
            return "nil";
    }
}

std::string Love2DBackend::generate_binary_expression(const Expression* expr, bool in_condition) {
    if (!expr || !expr->left || !expr->right) return "nil";

    std::string left = generate_expression(expr->left.get(), in_condition);
    std::string right = generate_expression(expr->right.get(), in_condition);
    std::string op = binary_op_to_lua(expr->binary_op);

    return "(" + left + " " + op + " " + right + ")";
}

std::string Love2DBackend::generate_unary_expression(const Expression* expr, bool in_condition) {
    if (!expr || !expr->operand) return "nil";

    std::string operand = generate_expression(expr->operand.get(), in_condition);
    std::string op = unary_op_to_lua(expr->unary_op);

    return "(" + op + operand + ")";
}

std::string Love2DBackend::generate_call_expression(const Expression* expr, bool in_condition) {
    if (!expr) return "nil";

    // Map function names to Love2D helpers
    std::string func_name = expr->function_name;
    if (func_name == "has_technology" || func_name == "has_structure" || func_name == "has_resources") {
        func_name = "GameData.helpers." + func_name;
    }

    std::string result = func_name + "(";
    bool first = true;
    for (const auto& arg : expr->arguments) {
        if (!first) result += ", ";
        result += generate_expression(arg.get(), in_condition);
        first = false;
    }
    result += ")";
    return result;
}

std::string Love2DBackend::generate_member_expression(const Expression* expr, bool in_condition) {
    if (!expr || !expr->object) return "nil";

    std::string obj = generate_expression(expr->object.get(), in_condition);
    return obj + "." + expr->member_name;
}

std::string Love2DBackend::generate_condition(const Condition* cond) {
    if (!cond) return "";

    std::stringstream lua;
    lua << "        " << cond->trigger << " = ";

    if (cond->expression && cond->expression->type != Expression::Type::BOOLEAN) {
        lua << "function(state) return "
            << generate_expression(cond->expression.get(), true)
            << " end,\n";
        return lua.str();
    }

    // Property-style conditions
    if (!cond->properties.empty()) {
        std::vector<std::string> checks;

        for (const auto& prop : cond->properties) {
            if (prop->name == "technologies" && prop->value &&
                prop->value->type == PropertyValue::Type::REFERENCE_LIST &&
                prop->value->reference_list) {
                for (const auto& tech : prop->value->reference_list->references) {
                    checks.push_back("GameData.helpers.has_technology(\"" + tech + "\", state)");
                }
            } else if (prop->name == "structures" && prop->value &&
                prop->value->type == PropertyValue::Type::REFERENCE_LIST &&
                prop->value->reference_list) {
                for (const auto& struct_id : prop->value->reference_list->references) {
                    checks.push_back("GameData.helpers.has_structure(\"" + struct_id + "\", state)");
                }
            } else if (prop->name == "resources" && prop->value &&
                prop->value->type == PropertyValue::Type::RESOURCE_MAP &&
                prop->value->resource_map) {
                checks.push_back("GameData.helpers.has_resources(" +
                    generate_resource_map(*prop->value->resource_map) + ", state)");
            }
        }

        if (!checks.empty()) {
            std::string condition_expr;
            for (size_t i = 0; i < checks.size(); ++i) {
                if (i > 0) condition_expr += " and ";
                condition_expr += checks[i];
            }
            lua << "function(state) return " << condition_expr << " end,\n";
            return lua.str();
        }
    }

    if (cond->expression) {
        lua << "function(state) return "
            << generate_expression(cond->expression.get(), true)
            << " end,\n";
    } else {
        lua << "true,\n";
    }

    return lua.str();
}

std::string Love2DBackend::binary_op_to_lua(Expression::BinaryOp op) const {
    switch (op) {
        case Expression::BinaryOp::ADD: return "+";
        case Expression::BinaryOp::SUB: return "-";
        case Expression::BinaryOp::MUL: return "*";
        case Expression::BinaryOp::DIV: return "/";
        case Expression::BinaryOp::MOD: return "%";
        case Expression::BinaryOp::EQ: return "==";
        case Expression::BinaryOp::NE: return "~=";
        case Expression::BinaryOp::GT: return ">";
        case Expression::BinaryOp::LT: return "<";
        case Expression::BinaryOp::GE: return ">=";
        case Expression::BinaryOp::LE: return "<=";
        case Expression::BinaryOp::AND: return "and";
        case Expression::BinaryOp::OR: return "or";
        default: return "+";
    }
}

std::string Love2DBackend::unary_op_to_lua(Expression::UnaryOp op) const {
    switch (op) {
        case Expression::UnaryOp::NOT: return "not ";
        case Expression::UnaryOp::NEG: return "-";
        default: return "";
    }
}

}
