#include "lua_backend.h"
#include <sstream>

namespace lex {

std::string LuaBackend::generate(const std::vector<std::unique_ptr<Definition>>& ast) {
    std::stringstream output;
    
    output << "-- Auto-generated by Lex Compiler\n";
    output << "-- Do not edit manually\n\n";
    
    for (const auto& def : ast) {
        if (def->definition_type == "structure") {
            output << generate_structure(*def);
        }
        // Add other definition types as needed
    }
    
    return output.str();
}

std::string LuaBackend::generate_structure(const Definition& structure) {
    std::stringstream lua;
    
    lua << "Buildings." << structure.identifier << " = {\n";
    
    // Get era from properties
    std::string era = get_string_property(structure, "era");
    if (!era.empty()) {
        lua << "    era = \"" << era << "\",\n";
    }
    
    // Get cost if present
    const ResourceMap* cost = get_resource_map_property(structure, "cost");
    if (cost) {
        lua << "    cost = " << generate_resource_map(*cost) << ",\n";
    }
    
    // Get production if present  
    const ResourceMap* production = get_resource_map_property(structure, "production");
    if (production) {
        lua << "    production = " << generate_resource_map(*production) << ",\n";
    }
    
    // Get description if present
    std::string desc = get_string_property(structure, "description");
    if (!desc.empty()) {
        lua << "    description = [[" << desc << "]],\n";
    }
    
    lua << "}\n\n";
    
    return lua.str();
}

std::string LuaBackend::generate_resource_map(const ResourceMap& map) {
    std::string lua = "{";
    bool first = true;
    for (const auto& [name, value] : map.resources) {
        if (!first) lua += ", ";
        lua += name + " = " + std::to_string(static_cast<int>(value));
        first = false;
    }
    lua += "}";
    return lua;
}

// ============================================================================
// Helper implementations
// ============================================================================

std::string LuaBackend::get_string_property(const Definition& def, const std::string& name) {
    for (const auto& prop : def.properties) {
        if (prop->name == name && prop->value) {
            if (prop->value->type == PropertyValue::Type::EXPRESSION && 
                prop->value->expression) {
                auto& expr = prop->value->expression;
                if (expr->type == Expression::Type::STRING) {
                    return std::get<std::string>(expr->value);
                } else if (expr->type == Expression::Type::REFERENCE) {
                    return expr->reference;
                }
            }
        }
    }
    return "";
}

int64_t LuaBackend::get_int_property(const Definition& def, const std::string& name, int64_t default_val) {
    for (const auto& prop : def.properties) {
        if (prop->name == name && prop->value) {
            if (prop->value->type == PropertyValue::Type::EXPRESSION && 
                prop->value->expression) {
                auto& expr = prop->value->expression;
                if (expr->type == Expression::Type::INTEGER) {
                    return std::get<int64_t>(expr->value);
                }
            }
        }
    }
    return default_val;
}

const ResourceMap* LuaBackend::get_resource_map_property(const Definition& def, const std::string& name) {
    for (const auto& prop : def.properties) {
        if (prop->name == name && prop->value) {
            if (prop->value->type == PropertyValue::Type::RESOURCE_MAP) {
                return prop->value->resource_map.get();
            }
        }
    }
    return nullptr;
}

}
