#include "lua_backend.h"

namespace lex {

std::string LuaBackend::generate(const std::vector<std::unique_ptr<Definition>>& ast) {
    std::string output;

    output += generate_header();
    output += "\n";

    for (const auto& def : ast) {
        if (auto* structure = dynamic_cast<const StructureDefinition*>(def.get())) {
            output += generate_structure(*structure);
            output += "\n";
        }
    }

    return output;
}

std::string LuaBackend::generate_header() {
    return "-- Auto-generated by Lex Compiler\n"
           "-- Do not edit manually\n";
}

std::string LuaBackend::generate_structure(const StructureDefinition& structure) {
    std::string lua;
    lua += "Buildings." + structure.identifier + " = {\n";
    lua += "    id = \"" + structure.identifier + "\",\n";

    if (!structure.era_ref.empty()) {
        lua += "    era = \"" + structure.era_ref + "\",\n";
    }

    if (structure.cost) {
        lua += "    cost = " + generate_resource_map(*structure.cost) + ",\n";
    }

    if (structure.production) {
        lua += "    production = " + generate_resource_map(*structure.production) + ",\n";
    }

    lua += "}\n";

    return lua;
}

std::string LuaBackend::generate_resource_map(const ResourceMap& map) {
    std::string lua = "{";
    bool first = true;
    for (const auto& [name, value] : map.resources) {
        if (!first) lua += ", ";
        lua += name + " = " + std::to_string(static_cast<int>(value));
        first = false;
    }
    lua += "}";
    return lua;
}

}
