#include "lua_backend.h"
#include <sstream>
#include <algorithm>

namespace lex {

std::string LuaBackend::type_to_table_name(const std::string& type) const {
    // Convert "structure" -> "Structures", "unit" -> "Units", etc.
    if (type.empty()) return "Items";

    std::string result = type;
    result[0] = static_cast<char>(std::toupper(result[0]));

    // Smart pluralization
    if (result.back() == 'y' && result.size() > 1) {
        // technology -> Technologies
        result.back() = 'i';
        result += "es";
    } else if (result.back() != 's') {
        result += 's';
    }
    return result;
}

std::string LuaBackend::generate(const std::vector<std::unique_ptr<Definition>>& ast) {
    std::stringstream output;

    output << "-- Auto-generated by Lex Compiler\n";
    output << "-- Do not edit manually\n\n";

    // First pass: collect all definition types
    for (const auto& def : ast) {
        seen_types_.insert(def->definition_type);
    }

    // Generate table declarations for each type (dynamic!)
    for (const auto& type : seen_types_) {
        std::string table_name = type_to_table_name(type);
        output << table_name << " = " << table_name << " or {}\n";
    }
    output << "\n";

    // Generate each definition
    for (const auto& def : ast) {
        output << generate_definition(*def);
    }

    return output.str();
}

std::string LuaBackend::generate_definition(const Definition& def) {
    // All types use the generic generator now
    return generate_generic(def);
}

std::string LuaBackend::generate_generic(const Definition& def) {
    std::stringstream lua;
    std::string table_name = type_to_table_name(def.definition_type);

    lua << table_name << "." << def.identifier << " = {\n";

    // Generate all properties dynamically
    for (const auto& prop : def.properties) {
        lua << "    " << prop->name << " = " << generate_property_value(*prop) << ",\n";
    }

    // Generate conditions if present
    if (!def.conditions.empty()) {
        lua << "    conditions = {\n";
        for (const auto& cond : def.conditions) {
            lua << generate_condition(cond.get());
        }
        lua << "    },\n";
    }

    lua << "}\n\n";

    // Generate condition checker function if needed
    if (!def.conditions.empty()) {
        lua << "function " << table_name << "." << def.identifier << ":check_conditions(game_state)\n";
        lua << "    local results = {}\n";
        for (const auto& cond : def.conditions) {
            if (cond->trigger == "available_if") {
                lua << "    results.available = results.available or ("
                    << generate_expression(cond->expression.get()) << ")\n";
            }
        }
        lua << "    return results\n";
        lua << "end\n\n";
    }

    return lua.str();
}

std::string LuaBackend::generate_property_value(const Property& prop) {
    if (!prop.value) return "nil";

    switch (prop.value->type) {
        case PropertyValue::Type::EXPRESSION:
            if (prop.value->expression) {
                return generate_expression(prop.value->expression.get());
            }
            return "nil";

        case PropertyValue::Type::RESOURCE_MAP:
            if (prop.value->resource_map) {
                return generate_resource_map(*prop.value->resource_map);
            }
            return "{}";

        case PropertyValue::Type::REFERENCE_LIST:
            if (prop.value->reference_list) {
                return generate_reference_list(*prop.value->reference_list);
            }
            return "{}";

        default:
            return "nil";
    }
}

std::string LuaBackend::generate_resource_map(const ResourceMap& map) {
    std::string lua = "{";
    bool first = true;
    for (const auto& [name, value] : map.resources) {
        if (!first) lua += ", ";
        lua += name + " = " + std::to_string(static_cast<int>(value));
        first = false;
    }
    lua += "}";
    return lua;
}

std::string LuaBackend::generate_reference_list(const ReferenceList& list) {
    std::string lua = "{";
    bool first = true;
    for (const auto& ref : list.references) {
        if (!first) lua += ", ";
        lua += "\"" + ref + "\"";
        first = false;
    }
    lua += "}";
    return lua;
}

// ============================================================================
// Expression Generation
// ============================================================================

std::string LuaBackend::generate_expression(const Expression* expr) {
    if (!expr) return "nil";

    switch (expr->type) {
        case Expression::Type::INTEGER:
            return std::to_string(std::get<int64_t>(expr->value));

        case Expression::Type::FLOAT:
            return std::to_string(std::get<double>(expr->value));

        case Expression::Type::STRING:
            return "\"" + std::get<std::string>(expr->value) + "\"";

        case Expression::Type::BOOLEAN:
            return std::get<bool>(expr->value) ? "true" : "false";

        case Expression::Type::REFERENCE:
            // References become game_state lookups
            return "game_state." + expr->reference;

        case Expression::Type::BINARY:
            return generate_binary_expression(expr);

        case Expression::Type::UNARY:
            return generate_unary_expression(expr);

        case Expression::Type::CALL:
            return generate_call_expression(expr);

        case Expression::Type::MEMBER:
            return generate_member_expression(expr);

        case Expression::Type::COLOR:
            if (std::holds_alternative<std::string>(expr->value)) {
                return "\"" + std::get<std::string>(expr->value) + "\"";
            }
            return "\"\"";

        case Expression::Type::NULL_VAL:
        default:
            return "nil";
    }
}

std::string LuaBackend::generate_binary_expression(const Expression* expr) {
    if (!expr || !expr->left || !expr->right) return "nil";

    std::string left = generate_expression(expr->left.get());
    std::string right = generate_expression(expr->right.get());
    std::string op = binary_op_to_lua(expr->binary_op);

    return "(" + left + " " + op + " " + right + ")";
}

std::string LuaBackend::generate_unary_expression(const Expression* expr) {
    if (!expr || !expr->operand) return "nil";

    std::string operand = generate_expression(expr->operand.get());
    std::string op = unary_op_to_lua(expr->unary_op);

    return "(" + op + operand + ")";
}

std::string LuaBackend::generate_call_expression(const Expression* expr) {
    if (!expr) return "nil";

    std::string result = expr->function_name + "(";
    bool first = true;
    for (const auto& arg : expr->arguments) {
        if (!first) result += ", ";
        result += generate_expression(arg.get());
        first = false;
    }
    result += ")";
    return result;
}

std::string LuaBackend::generate_member_expression(const Expression* expr) {
    if (!expr || !expr->object) return "nil";

    std::string obj = generate_expression(expr->object.get());
    return obj + "." + expr->member_name;
}

std::string LuaBackend::generate_condition(const Condition* cond) {
    if (!cond) return "";

    std::stringstream lua;
    lua << "        " << cond->trigger << " = ";

    if (cond->expression) {
        lua << "function(game_state) return "
            << generate_expression(cond->expression.get())
            << " end,\n";
    } else {
        lua << "true,\n";
    }

    return lua.str();
}

std::string LuaBackend::generate_condition_block(const Condition* cond) {
    // For complex conditions with properties in the block
    if (!cond) return "";

    std::stringstream lua;
    lua << "        {\n";
    lua << "            trigger = \"" << cond->trigger << "\",\n";

    if (cond->expression) {
        lua << "            check = function(game_state) return "
            << generate_expression(cond->expression.get())
            << " end,\n";
    }

    for (const auto& prop : cond->properties) {
        if (prop->value && prop->value->type == PropertyValue::Type::EXPRESSION) {
            lua << "            " << prop->name << " = "
                << generate_expression(prop->value->expression.get()) << ",\n";
        }
    }

    lua << "        },\n";
    return lua.str();
}

std::string LuaBackend::binary_op_to_lua(Expression::BinaryOp op) const {
    switch (op) {
        case Expression::BinaryOp::ADD: return "+";
        case Expression::BinaryOp::SUB: return "-";
        case Expression::BinaryOp::MUL: return "*";
        case Expression::BinaryOp::DIV: return "/";
        case Expression::BinaryOp::MOD: return "%";
        case Expression::BinaryOp::EQ: return "==";
        case Expression::BinaryOp::NE: return "~=";
        case Expression::BinaryOp::GT: return ">";
        case Expression::BinaryOp::LT: return "<";
        case Expression::BinaryOp::GE: return ">=";
        case Expression::BinaryOp::LE: return "<=";
        case Expression::BinaryOp::AND: return "and";
        case Expression::BinaryOp::OR: return "or";
        default: return "+";
    }
}

std::string LuaBackend::unary_op_to_lua(Expression::UnaryOp op) const {
    switch (op) {
        case Expression::UnaryOp::NOT: return "not ";
        case Expression::UnaryOp::NEG: return "-";
        default: return "";
    }
}

// ============================================================================
// Legacy Helper implementations (using Definition accessors now)
// ============================================================================

std::string LuaBackend::get_string_property(const Definition& def, const std::string& name) {
    auto result = def.get_string_property(name);
    return result.value_or("");
}

int64_t LuaBackend::get_int_property(const Definition& def, const std::string& name, int64_t default_val) {
    auto result = def.get_int_property(name);
    return result.value_or(default_val);
}

const ResourceMap* LuaBackend::get_resource_map_property(const Definition& def, const std::string& name) {
    return def.get_resource_map_property(name);
}

}
