#include "unity_backend.h"
#include <sstream>
#include <algorithm>

namespace lex {

std::string UnityBackend::type_to_class_name(const std::string& type) const {
    if (type.empty()) return "Item";

    std::string result = type;
    // PascalCase for C# classes
    result[0] = static_cast<char>(std::toupper(result[0]));

    // Remove pluralization for class name (singular)
    if (result.size() > 3 && result.substr(result.size() - 3) == "ies") {
        // technologies -> technology -> Technology
        result = result.substr(0, result.size() - 3) + "y";
    } else if (result.back() == 's' && result.size() > 1) {
        // structures -> Structure
        result.pop_back();
    }

    return result;
}

std::string UnityBackend::escape_string(const std::string& s) const {
    std::string result;
    for (char c : s) {
        switch (c) {
            case '"': result += "\\\""; break;
            case '\\': result += "\\\\"; break;
            case '\n': result += "\\n"; break;
            default: result += c;
        }
    }
    return result;
}

std::string UnityBackend::csharp_type(const Property& prop) const {
    if (!prop.value) return "object";

    switch (prop.value->type) {
        case PropertyValue::Type::EXPRESSION:
            if (prop.value->expression) {
                switch (prop.value->expression->type) {
                    case Expression::Type::STRING:
                    case Expression::Type::COLOR:
                        return "string";
                    case Expression::Type::INTEGER:
                        return "int";
                    case Expression::Type::FLOAT:
                        return "float";
                    case Expression::Type::BOOLEAN:
                        return "bool";
                    case Expression::Type::REFERENCE:
                        return "string";  // Reference as string ID
                    default:
                        return "string";
                }
            }
            return "object";
        case PropertyValue::Type::RESOURCE_MAP:
            return "ResourceCost";
        case PropertyValue::Type::REFERENCE_LIST:
            return "string[]";
        default:
            return "object";
    }
}

std::string UnityBackend::generate(const std::vector<std::unique_ptr<Definition>>& ast) {
    std::stringstream output;

    output << "// Auto-generated by Lex Compiler\n";
    output << "// Do not edit manually\n\n";
    output << "using UnityEngine;\n";
    output << "using System.Collections.Generic;\n\n";

    // Collect types and group definitions
    std::map<std::string, std::vector<const Definition*>> defs_by_type;
    for (const auto& def : ast) {
        seen_types_.insert(def->definition_type);
        defs_by_type[def->definition_type].push_back(def.get());
    }

    // Generate ResourceCost helper class if needed
    bool has_resources = false;
    for (const auto& def : ast) {
        for (const auto& prop : def->properties) {
            if (prop->value && prop->value->type == PropertyValue::Type::RESOURCE_MAP) {
                has_resources = true;
                break;
            }
        }
        if (has_resources) break;
    }

    if (has_resources) {
        output << "[System.Serializable]\n";
        output << "public class ResourceCost {\n";
        output << "    public int Gold;\n";
        output << "    public int Wood;\n";
        output << "    public int Coal;\n";
        output << "    public int Steel;\n";
        output << "    public int Energy;\n";
        output << "    public int Research;\n";
        output << "    public int Industry;\n";
        output << "}\n\n";
    }

    // Generate ScriptableObject class for each type
    for (const auto& [type_name, defs] : defs_by_type) {
        output << generate_scriptable_object_class(type_name, defs);
        output << "\n";
    }

    return output.str();
}

std::string UnityBackend::generate_scriptable_object_class(const std::string& type_name,
                                                             const std::vector<const Definition*>& defs) {
    std::stringstream cs;
    std::string class_name = type_to_class_name(type_name);

    // Collect all unique property names and types from all definitions
    std::map<std::string, std::string> properties;  // name -> C# type
    bool has_conditions = false;

    for (const auto& def : defs) {
        for (const auto& prop : def->properties) {
            if (properties.find(prop->name) == properties.end()) {
                properties[prop->name] = csharp_type(*prop);
            }
        }
        if (!def->conditions.empty()) {
            has_conditions = true;
        }
    }

    // Generate the data class
    cs << "[CreateAssetMenu(fileName = \"" << class_name << "Data\", menuName = \"Game/" << class_name << "\")]\n";
    cs << "public class " << class_name << "Data : ScriptableObject {\n";
    cs << "    public string id;\n";

    for (const auto& [prop_name, prop_type] : properties) {
        cs << "    public " << prop_type << " " << prop_name << ";\n";
    }

    if (has_conditions) {
        cs << "\n    [System.Serializable]\n";
        cs << "    public class Condition {\n";
        cs << "        public string trigger;\n";
        cs << "        public string expression;\n";
        cs << "    }\n";
        cs << "    public Condition[] conditions;\n";
    }

    cs << "}\n";

    return cs.str();
}

std::string UnityBackend::generate_property_value(const Property& prop) {
    if (!prop.value) return "null";

    switch (prop.value->type) {
        case PropertyValue::Type::EXPRESSION:
            if (prop.value->expression) {
                auto& expr = prop.value->expression;
                switch (expr->type) {
                    case Expression::Type::STRING:
                    case Expression::Type::COLOR:
                        return "\"" + escape_string(std::get<std::string>(expr->value)) + "\"";
                    case Expression::Type::INTEGER:
                        return std::to_string(std::get<int64_t>(expr->value));
                    case Expression::Type::FLOAT:
                        return std::to_string(std::get<double>(expr->value)) + "f";
                    case Expression::Type::BOOLEAN:
                        return std::get<bool>(expr->value) ? "true" : "false";
                    case Expression::Type::REFERENCE:
                        return "\"" + expr->reference + "\"";
                    default:
                        return "\"(expression)\"";
                }
            }
            return "null";
        case PropertyValue::Type::RESOURCE_MAP:
            return "new ResourceCost()";  // Would need individual field assignment
        case PropertyValue::Type::REFERENCE_LIST:
            return "new string[] {}";
        default:
            return "null";
    }
}

}
