// RPC Backend - Premium Tier (Core+)
// Generates Python and Go code for JSON-RPC protocols.
// Part of Lex-Plus package

#include "codegen/rpc_backend.hpp"
#include "lex/version.hpp"
#include <sstream>
#include <algorithm>
#include <cctype>

namespace lex {

std::string RPCBackend::generate(const std::vector<std::unique_ptr<Definition>>& ast) {
    parse_definitions(ast);
    
    std::stringstream output;
    
    output << "// ===========================================================================\n";
    output << "// Generated by Lex Compiler v" << LEX_VERSION << "\n";
    output << "// RPC Protocol - Python + Go\n";
    output << "// ===========================================================================\n\n";
    
    output << "=== PYTHON ===\n\n";
    output << generate_python();
    
    output << "\n=== GO ===\n\n";
    output << generate_go();
    
    return output.str();
}

void RPCBackend::parse_definitions(const std::vector<std::unique_ptr<Definition>>& ast) {
    for (const auto& def : ast) {
        if (def->definition_type == "method") {
            parse_method(*def);
        } else if (def->definition_type == "struct") {
            parse_struct(*def);
        }
    }
}

void RPCBackend::parse_method(const Definition& def) {
    MethodDef method;
    method.name = def.identifier;
    
    for (const auto& prop : def.properties) {
        if (!prop->value || !prop->value->expression) continue;
        
        if (prop->name == "input") {
            method.input_type = prop->value->expression->reference;
        } else if (prop->name == "output") {
            method.output_type = prop->value->expression->reference;
        }
    }
    
    methods_.push_back(method);
}

void RPCBackend::parse_struct(const Definition& def) {
    StructDef s;
    s.name = def.identifier;
    
    for (const auto& prop : def.properties) {
        if (!prop->value || !prop->value->expression) continue;
        
        std::string type;
        bool optional = false;
        
        // Get type from expression
        auto& expr = prop->value->expression;
        if (expr->type == Expression::Type::REFERENCE) {
            type = expr->reference;
        } else if (expr->type == Expression::Type::STRING) {
            type = std::get<std::string>(expr->value);
        }
        
        // Check for optional (?) suffix
        if (!type.empty() && type.back() == '?') {
            optional = true;
            type.pop_back();
        }
        
        s.field_names.push_back(prop->name);
        s.field_types.push_back(type);
        s.field_optional.push_back(optional);
    }
    
    structs_[s.name] = s;
}

// =============================================================================
// Python Generation
// =============================================================================

std::string RPCBackend::generate_python() {
    std::stringstream output;
    output << generate_python_types();
    output << "\n\n";
    output << generate_python_handlers();
    return output.str();
}

std::string RPCBackend::generate_python_types() {
    std::stringstream output;
    
    output << "\"\"\"\n";
    output << "Aurelius RPC Protocol - Auto-generated types\n";
    output << "Generated by Lex Compiler v" << LEX_VERSION << "\n";
    output << "\"\"\"\n\n";
    
    output << "from dataclasses import dataclass\n";
    output << "from typing import List, Optional, Dict, Any\n\n";
    
    for (const auto& [name, s] : structs_) {
        output << "@dataclass\n";
        output << "class " << name << ":\n";
        
        if (s.field_names.empty()) {
            output << "    pass\n";
        } else {
            for (size_t i = 0; i < s.field_names.size(); i++) {
                const auto& fname = s.field_names[i];
                const auto& ftype = s.field_types[i];
                bool is_opt = s.field_optional[i];
                
                output << "    " << fname << ": ";
                if (is_opt) {
                    output << "Optional[" << python_type(ftype) << "]";
                } else {
                    output << python_type(ftype);
                }
                output << "\n";
            }
        }
        output << "\n";
    }
    
    return output.str();
}

std::string RPCBackend::generate_python_handlers() {
    std::stringstream output;
    
    output << "\"\"\"\n";
    output << "Aurelius RPC Protocol - Auto-generated handlers\n";
    output << "Generated by Lex Compiler v" << LEX_VERSION << "\n";
    output << "\"\"\"\n\n";
    
    output << "from .types import *\n";
    output << "from .server import JsonRpcServer\n\n";
    
    // Generate handler interfaces
    output << "class RPCHandlerBase:\n";
    output << "    \"\"\"Base class for RPC handlers. Override methods to implement.\"\"\"\n\n";
    
    for (const auto& method : methods_) {
        std::string snake_name = to_snake_case(method.name);
        output << "    def handle_" << snake_name << "(self, params: dict) -> dict:\n";
        output << "        \"\"\"Handle " << method.name << " method.\"\"\"\n";
        output << "        raise NotImplementedError(\"" << method.name << " not implemented\")\n\n";
    }
    
    // Generate registration function
    output << "\n\ndef register_handlers(server: JsonRpcServer, handler: RPCHandlerBase):\n";
    output << "    \"\"\"Register all RPC handlers with the server.\"\"\"\n\n";
    
    for (const auto& method : methods_) {
        std::string snake_name = to_snake_case(method.name);
        output << "    def handle_" << snake_name << "_wrapper(params: dict) -> dict:\n";
        output << "        return handler.handle_" << snake_name << "(params)\n";
        output << "    server.register(\"" << method.name << "\", handle_" << snake_name << "_wrapper)\n\n";
    }
    
    return output.str();
}

std::string RPCBackend::python_type(const std::string& lex_type) {
    if (lex_type == "string") return "str";
    if (lex_type == "int") return "int";
    if (lex_type == "float") return "float";
    if (lex_type == "bool" || lex_type == "boolean") return "bool";
    if (lex_type == "Empty") return "None";
    
    // Array type: "Type[]"
    if (lex_type.size() >= 2 && lex_type.substr(lex_type.size() - 2) == "[]") {
        std::string inner = lex_type.substr(0, lex_type.size() - 2);
        return "List[" + python_type(inner) + "]";
    }
    
    // Custom type
    return lex_type;
}

// =============================================================================
// Go Generation
// =============================================================================

std::string RPCBackend::generate_go() {
    std::stringstream output;
    output << generate_go_types();
    output << "\n\n";
    output << generate_go_client();
    return output.str();
}

std::string RPCBackend::generate_go_types() {
    std::stringstream output;
    
    output << "// Code generated by Lex Compiler v" << LEX_VERSION << ". DO NOT EDIT.\n";
    output << "// Package rpc provides JSON-RPC types for Aurelius.\n\n";
    
    output << "package rpc\n\n";
    
    for (const auto& [name, s] : structs_) {
        output << "// " << name << " represents the " << name << " RPC type.\n";
        output << "type " << name << " struct {\n";
        
        for (size_t i = 0; i < s.field_names.size(); i++) {
            const auto& fname = s.field_names[i];
            const auto& ftype = s.field_types[i];
            bool is_opt = s.field_optional[i];
            
            std::string go_name = to_pascal_case(fname);
            std::string type_str = go_type(ftype);
            
            if (is_opt && !type_str.empty() && type_str[0] != '*' && type_str != "interface{}") {
                type_str = "*" + type_str;
            }
            
            output << "    " << go_name << " " << type_str;
            output << " `json:\"" << fname << "\"`\n";
        }
        output << "}\n\n";
    }
    
    return output.str();
}

std::string RPCBackend::generate_go_client() {
    std::stringstream output;
    
    output << "// Code generated by Lex Compiler v" << LEX_VERSION << ". DO NOT EDIT.\n\n";
    
    output << "package rpc\n\n";
    
    output << "import \"context\"\n\n";
    
    output << "// Client provides JSON-RPC client methods.\n";
    output << "type Client interface {\n";
    
    for (const auto& method : methods_) {
        std::string req_type = method.input_type.empty() ? "struct{}" : method.input_type;
        std::string res_type = method.output_type.empty() ? "struct{}" : method.output_type;
        std::string func_name = to_pascal_case(to_snake_case(method.name));
        
        output << "    " << func_name << "(ctx context.Context, req *" << req_type << ") (*" << res_type << ", error)\n";
    }
    
    output << "}\n\n";
    
    return output.str();
}

std::string RPCBackend::go_type(const std::string& lex_type) {
    if (lex_type == "string") return "string";
    if (lex_type == "int") return "int64";
    if (lex_type == "float") return "float64";
    if (lex_type == "bool" || lex_type == "boolean") return "bool";
    if (lex_type == "Empty") return "struct{}";
    
    // Array type: "Type[]"
    if (lex_type.size() >= 2 && lex_type.substr(lex_type.size() - 2) == "[]") {
        std::string inner = lex_type.substr(0, lex_type.size() - 2);
        return "[]" + go_type(inner);
    }
    
    // Custom type
    return lex_type;
}

// =============================================================================
// Helpers
// =============================================================================

std::string RPCBackend::strip_optional(const std::string& type) {
    if (!type.empty() && type.back() == '?') {
        return type.substr(0, type.size() - 1);
    }
    return type;
}

std::string RPCBackend::to_snake_case(const std::string& str) {
    std::string result;
    for (size_t i = 0; i < str.size(); i++) {
        char c = str[i];
        if (c == '/' || c == '.') {
            result += '_';
        } else if (std::isupper(static_cast<unsigned char>(c)) && i > 0) {
            result += '_';
            result += static_cast<char>(std::tolower(static_cast<unsigned char>(c)));
        } else {
            result += static_cast<char>(std::tolower(static_cast<unsigned char>(c)));
        }
    }
    return result;
}

std::string RPCBackend::to_pascal_case(const std::string& str) {
    std::string snake = to_snake_case(str);
    std::string result;
    bool capitalize = true;
    
    for (char c : snake) {
        if (c == '_') {
            capitalize = true;
        } else {
            if (capitalize) {
                result += static_cast<char>(std::toupper(static_cast<unsigned char>(c)));
                capitalize = false;
            } else {
                result += c;
            }
        }
    }
    
    return result;
}

// ============================================================================
// Auto-registration (only when Lex-Plus package is loaded)
// ============================================================================

namespace {
    struct RPCBackendAutoRegister {
        RPCBackendAutoRegister() {
            auto& registry = BackendRegistry::instance();
            
            registry.register_factory("rpc", []() {
                return std::make_unique<RPCBackend>();
            });
            
            registry.register_factory("rpc_python", []() {
                return std::make_unique<RPCBackend>();
            });
            
            registry.register_factory("rpc_go", []() {
                return std::make_unique<RPCBackend>();
            });
        }
    };
    
    // This will be constructed when the library is loaded
    // Only happens if Lex-Plus package is present
    static RPCBackendAutoRegister rpc_auto_register;
}

} // namespace lex
