// Unreal Engine Backend - Premium Tier (Core+)
// Part of Lex-Plus package

#include <sstream>
#include <algorithm>
#include "codegen/backend.hpp"
#include "codegen/unreal_backend.hpp"

namespace lex {

std::string UnrealBackend::name() const {
    return "unreal";
}

std::string UnrealBackend::file_extension() const {
    return ".h";  // C++ header for Unreal
}

std::string UnrealBackend::generate(const std::vector<std::unique_ptr<Definition>>& ast) {
    std::stringstream output;

    output << "// Auto-generated by Lex Compiler - Unreal Engine Backend\n";
    output << "// Part of Lex-Plus Premium Tier\n";
    output << "// Do not edit manually\n\n";

    output << "#pragma once\n\n";
    output << "#include \"CoreMinimal.h\"\n";
    output << "#include \"GameData.generated.h\"\n\n";

    // TODO: Implement full Unreal backend
    // - Generate UCLASS, USTRUCT, UENUM
    // - Generate FTableRowBase for data tables
    // - Generate Blueprint-accessible properties

    for (const auto& def : ast) {
        if (def) {
            // Placeholder: just output the definition name
            output << "// Definition: " << def->identifier << "\n";
        }
    }

    return output.str();
}

// ============================================================================
// Auto-registration
// ============================================================================

namespace {
    struct UnrealBackendAutoRegister {
        UnrealBackendAutoRegister() {
            auto& registry = BackendRegistry::instance();

            registry.register_factory("unreal", []() {
                return std::make_unique<UnrealBackend>();
            });
        }
    };

    // This will be constructed when the library is loaded
    // Only happens if Lex-Plus package is present
    static UnrealBackendAutoRegister unreal_auto_register;
}

} // namespace lex
