-- Auto-generated by Lex Compiler
-- Do not edit manually

Eras = Eras or {}
Resources = Resources or {}
Structures = Structures or {}
Technologies = Technologies or {}
Units = Units or {}

Resources.Gold = {
    name = "Gold",
    category = "currency",
    description = "Primary currency for construction and maintenance",
}

Resources.Wood = {
    name = "Wood",
    category = "material",
    description = "Basic construction material",
}

Resources.Coal = {
    name = "Coal",
    category = "fuel",
    description = "Fuel for steam machines and factories",
}

Resources.Steel = {
    name = "Steel",
    category = "material",
    description = "Advanced construction material",
}

Resources.Energy = {
    name = "Energy",
    category = "utility",
    description = "Power for advanced structures",
}

Resources.Industry = {
    name = "Industry",
    category = "production",
    description = "Industrial output capacity",
}

Resources.Research = {
    name = "Research",
    category = "knowledge",
    description = "Scientific research points",
}

Eras.Ancient = {
    name = "Ancient Era",
    period = "3000 BCE - 500 CE",
    description = "The dawn of civilization. Basic agriculture, simple tools, and the first cities.",
    atmosphere = "pastoral, sunny, peaceful",
    music = "ancient_ost",
    dominant_color = "#D4A574",
}

Eras.Steampunk = {
    name = "Steampunk Era",
    period = "1850 - 1920",
    description = "The age of steam, mechanical engineering, and industrial revolution.",
    atmosphere = "industrial, foggy, mechanical",
    music = "steampunk_ost",
    dominant_color = "#8B6914",
}

Structures.Farm = {
    era = game_state.Ancient,
    name = "Farm",
    description = "Produces food and basic resources for your civilization.",
    cost = {Gold = 30, Wood = 15},
    production = {Gold = 5},
    maintenance = {Gold = 1},
}

Structures.Barracks = {
    era = game_state.Ancient,
    name = "Barracks",
    description = "Trains basic military units.",
    cost = {Gold = 50, Wood = 25},
    maintenance = {Gold = 3},
}

Structures.Library = {
    era = game_state.Ancient,
    name = "Library",
    description = "Generates research points for technological advancement.",
    cost = {Gold = 80, Wood = 40},
    production = {Research = 10},
    maintenance = {Gold = 5},
}

Structures.SteamFactory = {
    era = game_state.Steampunk,
    name = "Steam Factory",
    description = "Converts coal into energy and industrial output.",
    cost = {Coal = 8, Gold = 50, Steel = 5},
    production = {Energy = 15, Industry = 10},
    maintenance = {Coal = 2, Gold = 5},
    conditions = {
        available_if = function(game_state) return has_technology(game_state.SteamEngine) end,
    },
}

function Structures.SteamFactory:check_conditions(game_state)
    local results = {}
    results.available = results.available or (has_technology(game_state.SteamEngine))
    return results
end

Structures.ResearchLab = {
    era = game_state.Steampunk,
    name = "Research Laboratory",
    description = "Advanced research facility for modern technologies.",
    cost = {Energy = 5, Gold = 100, Steel = 10},
    production = {Research = 25},
    maintenance = {Coal = 3, Gold = 10},
}

Units.Warrior = {
    era = game_state.Ancient,
    name = "Warrior",
    type = "infantry",
    description = "Basic infantry unit.",
    attack = 5,
    defense = 3,
    movement = 2,
    cost = {Gold = 20},
    maintenance = {Gold = 2},
}

Units.Archer = {
    era = game_state.Ancient,
    name = "Archer",
    type = "ranged",
    description = "Ranged unit with good attack but weak defense.",
    attack = 7,
    defense = 1,
    movement = 2,
    cost = {Gold = 25, Wood = 5},
    maintenance = {Gold = 2},
}

Units.SteamTank = {
    era = game_state.Steampunk,
    name = "Steam Tank",
    type = "armored",
    description = "Heavily armored steam-powered vehicle.",
    attack = 15,
    defense = 12,
    movement = 1,
    cost = {Coal = 10, Gold = 80, Steel = 15},
    maintenance = {Coal = 3, Gold = 8},
}

Technologies.SteamEngine = {
    era = game_state.Steampunk,
    name = "Steam Engine",
    description = "Harness the power of steam for industry and transportation.",
    research_cost = 100,
    unlocks = {"SteamFactory", "SteamTank"},
}

Technologies.IndustrialChemistry = {
    era = game_state.Steampunk,
    name = "Industrial Chemistry",
    description = "Advanced chemical processes for industry.",
    research_cost = 150,
    prerequisites = {"SteamEngine"},
    unlocks = {"ResearchLab"},
}

