# Auto-generated by Lex Compiler
# Source: rpg_data.lex
# Regenerate: lexc rpg_data.lex -t gd -o . --types item,character,location
class_name GameData extends Resource

var characters = {}
var items = {}
var locations = {}

func _init():
	items["Sword"] = {
		"id": "Sword",
		"type": "item",
		"name": "Iron Sword",
		"rarity": "common",
		"damage": 15,
		"cost": {"Gold": 100},
	}
	items["Shield"] = {
		"id": "Shield",
		"type": "item",
		"name": "Wooden Shield",
		"rarity": "common",
		"defense": 10,
		"cost": {"Gold": 50},
	}
	items["Health_Potion"] = {
		"id": "Health_Potion",
		"type": "item",
		"name": "Health Potion",
		"rarity": "common",
		"heal": 50,
		"cost": {"Gold": 25},
	}
	characters["Warrior"] = {
		"id": "Warrior",
		"type": "character",
		"name": "Warrior",
		"health": 100,
		"attack": 20,
		"defense": 10,
	}
	characters["Mage"] = {
		"id": "Mage",
		"type": "character",
		"name": "Mage",
		"health": 60,
		"attack": 35,
		"defense": 5,
	}
	locations["Village"] = {
		"id": "Village",
		"type": "location",
		"name": "Peaceful Village",
		"level": 1,
		"description": "A safe place to rest and trade.",
	}
	locations["Forest"] = {
		"id": "Forest",
		"type": "location",
		"name": "Dark Forest",
		"level": 5,
		"description": "Wolves and bandits lurk in the shadows.",
	}
	locations["Dungeon"] = {
		"id": "Dungeon",
		"type": "location",
		"name": "Dark Dungeon",
		"level": 10,
		"description": "A dangerous place full of monsters and treasure.",
	}

# Helper functions
func get_item(id: String) -> Dictionary:
	return items.get(id, {})

func get_character(id: String) -> Dictionary:
	return characters.get(id, {})

func get_location(id: String) -> Dictionary:
	return locations.get(id, {})
