export { Hero } from './Hero'
export { ProblemSolution } from './ProblemSolution'
export { Stats } from './Stats'
export { Install } from './Install'
export { Backends } from './Backends'
export { Features } from './Features'
export { CTA } from './CTA'
export { Tiers } from './Tiers'
export * from './data'
