import { useState, useEffect, useCallback } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { CodeBlock } from './CodeBlock';
import { useLanguage } from '../i18n/LanguageContext';

interface Example {
  input: string;
  outputs: {
    lua: string;
    json: string;
    csharp: string;
    gdscript: string;
  };
}

const examples: Example[] = [
  {
    input: `// Game unit definition
unit Swordsman {
    name: "Swordsman"
    era: ancient
    cost {
        gold: 80
        wood: 20
    }
    stats {
        health: 100
        damage: 15
        speed: 3
        range: 1
    }
    requires: [barracks]
    abilities: [slash, shield_block]
}`,
    outputs: {
      lua: `-- Auto-generated by Lex Compiler
units = units or {}

units.swordsman = {
    name = "Swordsman",
    era = "ancient",
    cost = {
        gold = 80,
        wood = 20
    },
    stats = {
        health = 100,
        damage = 15,
        speed = 3,
        range = 1
    },
    requires = { "barracks" },
    abilities = { "slash", "shield_block" }
}`,
      json: `{
  "units": {
    "swordsman": {
      "name": "Swordsman",
      "era": "ancient",
      "cost": {
        "gold": 80,
        "wood": 20
      },
      "stats": {
        "health": 100,
        "damage": 15,
        "speed": 3,
        "range": 1
      },
      "requires": ["barracks"],
      "abilities": ["slash", "shield_block"]
    }
  }
}`,
      csharp: `// Auto-generated by Lex Compiler
[CreateAssetMenu(fileName = "Swordsman", menuName = "Game/Units/Swordsman")]
public class Swordsman : UnitData
{
    public Swordsman()
    {
        Name = "Swordsman";
        Era = EraType.Ancient;
        Cost = new Cost { Gold = 80, Wood = 20 };
        Stats = new Stats 
        { 
            Health = 100, 
            Damage = 15, 
            Speed = 3, 
            Range = 1 
        };
        Requires = new[] { "barracks" };
        Abilities = new[] { "slash", "shield_block" };
    }
}`,
      gdscript: `# Auto-generated by Lex Compiler
class_name SwordsmanData extends Resource

@export var name: String = "Swordsman"
@export var era: String = "ancient"
@export var cost: Dictionary = {
    "gold": 80,
    "wood": 20
}
@export var stats: Dictionary = {
    "health": 100,
    "damage": 15,
    "speed": 3,
    "range": 1
}
@export var requires: Array[String] = ["barracks"]
@export var abilities: Array[String] = ["slash", "shield_block"]`
    }
  },
  {
    input: `// Technology definition
technology Agriculture {
    name: "Agriculture"
    era: ancient
    cost {
        science: 100
    }
    unlocks: [farm, granary]
    effect {
        food_bonus: 0.25
    }
}`,
    outputs: {
      lua: `-- Auto-generated by Lex Compiler
technologies = technologies or {}

technologies.agriculture = {
    name = "Agriculture",
    era = "ancient",
    cost = {
        science = 100
    },
    unlocks = { "farm", "granary" },
    effect = {
        food_bonus = 0.25
    }
}`,
      json: `{
  "technologies": {
    "agriculture": {
      "name": "Agriculture",
      "era": "ancient",
      "cost": { "science": 100 },
      "unlocks": ["farm", "granary"],
      "effect": { "food_bonus": 0.25 }
    }
  }
}`,
      csharp: `// Auto-generated by Lex Compiler
[CreateAssetMenu(fileName = "Agriculture", menuName = "Game/Technologies/Agriculture")]
public class Agriculture : TechnologyData
{
    public Agriculture()
    {
        Name = "Agriculture";
        Era = EraType.Ancient;
        Cost = new Cost { Science = 100 };
        Unlocks = new[] { "farm", "granary" };
        Effect = new Effect { FoodBonus = 0.25f };
    }
}`,
      gdscript: `# Auto-generated by Lex Compiler
class_name AgricultureData extends Resource

@export var name: String = "Agriculture"
@export var era: String = "ancient"
@export var cost: Dictionary = {"science": 100}
@export var unlocks: Array[String] = ["farm", "granary"]
@export var effect: Dictionary = {"food_bonus": 0.25}`
    }
  }
];

type Target = 'lua' | 'json' | 'csharp' | 'gdscript';

const targetIcons: Record<Target, string> = {
  lua: '[ LUA ]',
  json: '[ JSN ]',
  csharp: '[ C#_ ]',
  gdscript: '[ GDS ]'
};

const targetNames: Record<Target, string> = {
  lua: 'Lua',
  json: 'JSON',
  csharp: 'C# (Unity)',
  gdscript: 'GDScript (Godot)'
};

export function CodeTransformer() {
  const { t } = useLanguage();
  const [currentExample, setCurrentExample] = useState(0);
  const [selectedTarget, setSelectedTarget] = useState<Target>('lua');
  const [phase, setPhase] = useState<'input' | 'transform' | 'output'>('input');
  const [isTyping, setIsTyping] = useState(true);
  const [isPaused, setIsPaused] = useState(false);

  const example = examples[currentExample];

  const handleInputComplete = useCallback(() => {
    setIsTyping(false);
    setTimeout(() => {
      setPhase('transform');
      setTimeout(() => {
        setPhase('output');
        setIsTyping(true);
      }, 1200);
    }, 400);
  }, []);

  const handleOutputComplete = useCallback(() => {
    setIsTyping(false);
    // Pause before next cycle
    setTimeout(() => {
      setPhase('input');
      setIsTyping(true);
      // Cycle through targets
      const targets: Target[] = ['lua', 'json', 'csharp', 'gdscript'];
      const currentIndex = targets.indexOf(selectedTarget);
      const nextTarget = targets[(currentIndex + 1) % targets.length];
      setSelectedTarget(nextTarget);
      // Cycle through examples
      if (nextTarget === 'lua') {
        setCurrentExample((prev) => (prev + 1) % examples.length);
      }
    }, 2000);
  }, [selectedTarget]);

  // Auto-start on mount
  useEffect(() => {
    setPhase('input');
    setIsTyping(true);
  }, []);

  // Pause/Resume with spacebar
  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.code === 'Space') {
        e.preventDefault();
        setIsPaused((prev) => !prev);
      }
    };
    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, []);

  return (
    <div className="transformer">
      <div style={{ textAlign: 'center', marginBottom: '24px' }}>
        <p className="hint" style={{ color: '#94a3b8', fontSize: '0.8rem', fontFamily: '"JetBrains Mono", monospace' }}>{t('teaser.hint')}</p>
      </div>

      <div className="target-indicator" style={{ display: 'inline-flex', alignItems: 'center', gap: '8px', padding: '8px 16px', background: 'rgba(177,34,229,0.1)', border: '1px solid #b122e5', borderRadius: '4px', margin: '0 auto 24px', boxShadow: '0 0 15px rgba(177,34,229,0.2)' }}>
        <span className="target-icon" style={{ color: '#b122e5', fontWeight: 'bold', fontFamily: '"JetBrains Mono", monospace' }}>{targetIcons[selectedTarget]}</span>
        <span className="target-name" style={{ color: '#e2e8f0', textTransform: 'uppercase', fontSize: '0.9rem', letterSpacing: '1px' }}>{targetNames[selectedTarget]}</span>
      </div>

      <div className="transformer-content">
        <div className="code-panel input-panel" style={{ display: 'flex', flexDirection: 'column' }}>
          <CodeBlock
            code={example.input}
            language="lex"
            title="INPUT :: game.lex"
            typing={phase === 'input' && isTyping && !isPaused}
            typingSpeed={25}
            onTypingComplete={handleInputComplete}
          />
        </div>

        <div className="transform-arrow">
          <AnimatePresence>
            {phase === 'transform' && (
              <motion.div
                initial={{ opacity: 0, x: -20 }}
                animate={{ opacity: 1, x: 0 }}
                exit={{ opacity: 0, x: 20 }}
                transition={{ duration: 0.2 }}
                className="arrow-icon"
                style={{ color: '#b122e5', fontSize: '2rem', textShadow: '0 0 10px #b122e5', fontWeight: 'bold' }}
              >
                &gt;&gt;
              </motion.div>
            )}
          </AnimatePresence>
          {phase === 'output' && !isTyping && (
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              className="arrow-icon done"
              style={{ color: '#22c55e', fontSize: '2rem', textShadow: '0 0 10px #22c55e', fontWeight: 'bold' }}
            >
              OK
            </motion.div>
          )}
        </div>

        <div className="code-panel output-panel" style={{ display: 'flex', flexDirection: 'column' }}>
          <CodeBlock
            code={phase === 'output' ? example.outputs[selectedTarget] : ''}
            language={selectedTarget === 'csharp' ? 'csharp' : selectedTarget}
            title={`OUTPUT :: ${targetNames[selectedTarget]}`}
            typing={phase === 'output' && isTyping && !isPaused}
            typingSpeed={2}
            onTypingComplete={handleOutputComplete}
          />
        </div>
      </div>

      <div className="progress-dots">
        {examples.map((_, i) => (
          <span
            key={i}
            className={`dot ${currentExample === i ? 'active' : ''}`}
          />
        ))}
      </div>

      {isPaused && (
        <div className="pause-overlay">
          <span>⏸️ Paused</span>
        </div>
      )}
    </div>
  );
}
